### PR TITLE
Skil 151

### PR DESCRIPTION
**Pull request by brianlugo1**
Todos Completed:
[x] Implement Login.js component.
[x] Connect /login route to return Login.js component.
[x] Store access_token, refresh_token, and user_id in a cookie.
[x] Use the cookie to retrieve access_token, refresh_token, and user_id when needed.
[x] Use the access_token and user_id to retrieve courses.
[x] Implemented Logout.js component.
[x] Connected Logout button with Logout.js component.
[x] Implemented getting a new access_token when expired using the refresh_token.

### CODE REVIEW

**Review by aldiux4you — APPROVED** [review]
LGTM!

**Comment by sah0017** [comment]
@Etl1117 when do you think you can complete this code review?

**Comment by Etl1117** [comment]
There are problems running the server with the current demo that we have. I'm getting messages such as "attempting to run python3 dbcreate.py failed". Essentially, setting up the database with the demo data is not working properly, which means I'm not able to log in with a test user.

**Review by Etl1117 — CHANGES_REQUESTED** [review]
Linux automatic installation of server needs to be completed before merging.

**Comment by brianlugo1** [comment]
The pull request for UI-Proposal—aldo containing updates to automatically install redis-server for MacOS and Linux has been merged to SKIL-49! I have went ahead and merged SKIL-49 to SKIL-151 (aka this branch) with the updated changes!

**Review by Wrimo — APPROVED** [review]
I wonder if there's a more modular way to deal with checking if logged in for every fetch. Maybe it could be in a function in utility.js to prevent having the same logic in a lot of files? Overall though, LGTM!

**Comment by brianlugo1** [comment]
@Wrimo I already wrote a function called genericResourceFetch() that modularizes the log in process in SKIL-169! I have already made a pull request for SKIL-169. However, I have been waiting for this pull request to be reviewed, approved, and merged before continuing to the pull request for SKIL-169! @sah0017 I will now be merging this pull request!

**Comment by brianlugo1** [comment]
LGTM!

**Pull request merged**
