### PR TITLE
SKIL-566

### PR DESCRIPTION
**Pull request by sah0017**

### CODE REVIEW

**Review by hmnur3636 — CHANGES_REQUESTED** [review]
The helper text seems fine but the assessment task data is still not saving properly.

**Comment by sah0017** [comment]
@hmnur3636 are you seeing any error messages in your BackEnd terminal?

**Review by hmnur3636 — APPROVED** [review]
LGTM

**Review by aparriaran — APPROVED** [review]
@sah0017 LGTM

**Comment by aparriaran** [comment]
@sah0017 I am going to merge this PR

**Pull request merged**
