### PR TITLE
SKIL-265

### PR DESCRIPTION
**Pull request by aldiux4you**
Added Logic to Hide password to team on Inv AT
Fix Unit of Assessment bug that marked both options.

### CODE REVIEW

**Comment by aldiux4you** [comment]
Added Logic to Hide password to team on Inv AT
Fix Unit of Assessment bug that marked both options.

**Review by brianlugo1 — APPROVED** [review]
@sah0017 LGTM!

**Review by aparriaran — APPROVED** [review]
@sah0017 LGTM!

**Comment by brianlugo1** [comment]
@sah0017 I am going to go ahead and merge this PR with two approved code reviews!

**Pull request merged**
