### PR TITLE
Skil 50

### PR DESCRIPTION
**Pull request by brianlugo1**

### CODE REVIEW

**Comment by Etl1117** [comment]
When running the back-end and front-end, I was having problems with creating user from both servers. From my perspective, I do not believe this will need fixing since Jeremy's branch has been approved to be merged into master. Once Jeremy's branch is merged into master, I believe that the user routes will be working properly.

In order to avoid breaking master, I'm going to wait to approve this pull request until we have discussed it tomorrow morning.

**Comment by sah0017** [comment]
@Etl1117 I'm seeing merge conflicts.

**Comment by brianlugo1** [comment]
@sah0017 Merge conflicts fixed!!!

**Comment by brianlugo1** [comment]
@sah0017 Yes!

**Pull request merged**
