### PR TITLE
SKIL-436

### PR DESCRIPTION
**Pull request by ebanderson3**
TODOs completed:
- Added ability for superadmin to delete a user from the edit user menu.
- Updated Schema to restrict admin deletion if they are associated to a course.

### CODE REVIEW

**Review by rtkells — APPROVED** [review]
@sah0017 LGTM!

**Comment by zaramalik03** [comment]
LGTM!

**Review by aparriaran — APPROVED** [review]
@sah0017  LGTM!

**Comment by aparriaran** [comment]
@sah0017 I am going to merge this PR!

**Pull request merged**
