### PR TITLE
Fixes to loginDriver.py and test1

### PR DESCRIPTION
**Pull request by mekealbrown**
get_invalid_email_alert was looking for 'invalid email' message and password too short message. 'Invalid Email' would never show if password entered is too short. The password length was adjusted in the login method used so that the get_password_alert method is doing what is should: check for invalid email. Additionally, get_password_alert was using the incorrect Selenium locator to find error: this has been corrected. All tests currently pass with no errors.

### CODE REVIEW

**Comment by mekealbrown** [comment]
I had left comments I made for myself to help with the bug fixes on the files. The comments were present on the first commits and were removed in the last commit of this pull request.

**Comment by mr21Awesomeness** [comment]
Added a commit that passes all tests for test2_createProject_test.py.

**Comment by mr21Awesomeness** [comment]
Added a commit where I wrote all new tests for the "TestSignUp" class in "test0_signUp_test.py" and wrote new member functions for the "SignUp" class in "signUpDriver.py".

**Comment by mr21Awesomeness** [comment]
Added a commit where I wrote all new tests for the "TestLogIn" class in "test1_login_test.py" and wrote new member functions for the "LogIn" class in "loginDriver.py".

**Pull request merged**
