### PR TITLE
Skil 17

### PR DESCRIPTION
**Pull request by Etl1117**
The following pull request is for:

Rubric_routes.py:
- Both get all and get routes were created with error handling
- Rubrics now appear in a specific JSON format for the front end to pull

category.py, oc.py, and suggestions.py
- These models were updated with specific functions that the get routes utilize to return the correct formatted JSON

### CODE REVIEW

**Comment by brianlugo1** [comment]
@sah0017 I successfully updated the frontend View Assessment Task page to display rubrics according to the new format and naming convention! However, I noticed that we are missing some data about each rubric. Specifically, the different rating options that correspond to values ranging from 0 to 5. An example is that all the categories for the Critical Thinking rubric use the ratings No evidence, Minimally, Partially, and Completely, each corresponding to specific rating values. However in the Interpersonal Communication rubric the different ratings map to No evidence, Rarely, Sometimes, Consistently. We would need to add a new table that contains the different Rating names per category basis.

**Comment by brianlugo1** [comment]
@sah0017 I also saw that all the rubrics have a rating, Observable Characteristics, and Suggestions for Improvements section. However, the Critical Thinking rubric has a rating, Observable Characteristics, and Things to do to improve. We could need to update the Category table to store the name for the group of Observable Characteristics and Suggestions for Improvements.

**Comment by sah0017** [comment]
@brianlugo1 @Etl1117 I put a question in the Google doc that I share with Dr. Ruder and Dr. Lantz to ask about the wording.  I suspect that they would prefer to have it be all the same rather than vary from one rubric to another.  If that is the case, I have asked them which one is the correct wording.  I'll let you know when I hear from them.

**Comment by sah0017** [comment]
@brianlugo1 @Etl1117 from Dr. Lantz:
"The title of that segment should always be “suggestion for Improvement”.   As for the words that accompany the ratings, they do differ across the rubrics and categories, though we tried to limit the variations that were used.  I don’t think that one uniform set of descriptors be used - we tried to do this, and it just doesn’t’ make sense for some categories.  But for sake of sanity of the users, we tried to use a very small number of sets repeatedly.  If you find that to not be true, please bring it to our attention (or if you see some places where a more common set could replace what is being shown..)"

So, Suggestions for Improvement doesn't need an additional table, but it looks like the Ratings names will need one.  We might have 2 fields, one for Full Screen, and one for an abbreviation that would be used on a phone.

**Comment by sah0017** [comment]
@brianlugo1 is this truly ready to merge?  If I merge it, will you have to fix another PR somewhere else?

**Comment by Etl1117** [comment]
@sah0017 No, this branch isn't ready to merge. Initially, this pull request was created when we believed that the rubric routes were finished. However, after review, it was determined that some updates were needed to be made, which I'm currently working on right now.

**Pull request closed without merging**
