### PR TITLE
SKIL-429

### PR DESCRIPTION
**Pull request by jcallison1**
TODOs Completed:
- Removed timeToWait variable in utilities.js.
- Removed artifical delays in genericResourceGET/PUT/POST functions.
- Improved responsiveness of web app.

### CODE REVIEW

**Comment by jcallison1** [comment]
This change seems to cause several tests to fail. Further investigation is required before it can be merged.

**Comment by jcallison1** [comment]
All tests now pass and this PR is now ready to review.

**Comment by Adham-Alammuri** [comment]
LGTM!

**Review by aparriaran — APPROVED** [review]
@sah0017 LGTM!

**Review by Adham-Alammuri — APPROVED** [review]
LGTM!

**Comment by aparriaran** [comment]
@sah0017 I am going to merge this PR!

**Pull request merged**
