### PR TITLE
SKIL-306

### PR DESCRIPTION
**Pull request by aparriaran**
TODOs Completed:
-updated the reporting dashboard so that the dropdown of the assessment tasks are ONLY contains the assessments of the chosen course that is selected.

### CODE REVIEW

**Review by brianlugo1 — APPROVED** [review]
@sah0017 LGTM!

**Comment by rtkells** [comment]
@sah0017 LGTM!

**Review by rtkells — APPROVED** [review]
@sah0017 LGTM!

**Comment by brianlugo1** [comment]
@sah0017 I am going to go ahead and merge this PR with two approved code reviews!

**Pull request merged**
