### PR TITLE
Updating requirements.txt

### PR DESCRIPTION
**Pull request by brianlugo1**
Upon creating a new virtual machine running Ubuntu 64-bit 22.04.3 to check cross-platform compatibility for development, I encountered issues while attempting to run the Backend Flask Server. I have fixed these issues and now the Backend Flask Server runs as expected. I can confirm the changes I made to the Backend Flask Server work with MacOS as well. However, I do not have confirmation for Windows. Once I have a confirmation for Windows, we can merge the changes I made to master!

### CODE REVIEW

**Comment by brianlugo1** [comment]
@Wrimo Can you confirm that the Frontend and Backend server runs in this branch using your Windows machine?

**Comment by aldiux4you** [comment]
LGTM!

**Review by aldiux4you — APPROVED** [review]

**Review by Wrimo — APPROVED** [review]
I can confirm that this branch runs for me on Windows, both natively and in WSL.

LGTM!

**Comment by brianlugo1** [comment]
@sah0017 This branch is ready to be merged! LGTM!

**Pull request merged**
