### PR TITLE
Added logger implementation and logs/ directory.

### PR DESCRIPTION
**Pull request by malloc-nbytes**
Added the ability to log messages/errors.

### CODE REVIEW

**Comment by sah0017** [comment]
@malloc-nbytes you need to request @brianlugo1 and @Wrimo to do a code review.

Is there a mechanism to clear the logs after a certain period of time?  We don't want runaway logs that take up all our disk space.

**Comment by malloc-nbytes** [comment]
@sah0017 It does not, thank you for pointing that out. Would clearing it once a week be a good time frame?

**Comment by sah0017** [comment]
I think we could go longer than that.  I'd probably save it for 90 days.
That way if there are issues over the summer, it doesn't get cleared out
before someone can get to it to review what's there.  And this should be
low enough volume that 90 days won't fill it too much.

**Review by Wrimo — APPROVED** [review]
LGTM

**Pull request merged**
