### PR TITLE
added the rewrite for setupEnv2.py

### PR DESCRIPTION
**Pull request by malloc-nbytes**
The rewrite for setupEnv.py. Supported flags are:
  * -h, --help -> shows the usage
  * -r, --reset -> resets the db
  * -i, --install -> installs deps
  * -s, --start -> starts flask
  * -d, --demo -> loads demo.

### CODE REVIEW

**Review by Wrimo — APPROVED** [review]
LGTM

**Review by brianlugo1 — APPROVED** [review]
LGTM!

**Comment by brianlugo1** [comment]
@sah0017 This pull request has received two approved code reviews! This pull request is ready to be merged!

**Comment by sah0017** [comment]
@brianlugo1 @Wrimo @aldiux4you pull request is merged and ready to be pulled to your branches

**Comment by Wrimo** [comment]
Just encountered an error using the new setupEnv.py. If an error occurs while resetting the db, it will report "Invalid argument: reset" instead of saying something about an error occurring while resetting the database.

**Pull request merged**
