### PR TITLE
SKIL-388

### PR DESCRIPTION
**Pull request by Adham-Alammuri**
TODOs Completed:
- Removed the ability to hit start for team assessment tasks for courses that do not teams
- added a special message to inform the user why the button is disabled

### CODE REVIEW

**Review by aparriaran — APPROVED** [review]
@sah0017 LGTM!

**Review by jcallison1 — APPROVED** [review]
@sah0017 LGTM

**Comment by aparriaran** [comment]
@sah0017 LGTM!

**Comment by aparriaran** [comment]
@sah0017 I am going to merge this PR!

**Pull request merged**
