### PR TITLE
SKIL-440

### PR DESCRIPTION
**Pull request by hmnur3636**
- Reporting Page now fits on the screen
- Fixed bug in Ratings that made it disappear when showRatings is false and added a place holder icon when it is false.
- Improvements now has a placeholder image when showSuggestions is false. And fixed ShowSuggestions since it was accidentally written out of the code when tabs stopped being used in Improvements/Characteristics.

### CODE REVIEW

**Review by jcallison1 — CHANGES_REQUESTED** [review]
Looks like you have some merge conflicts in `Reporting/ViewAssessmentStatus/ViewAssessmentStatus.js` that need to be taken care of before this can be merged.

**Review by aparriaran — APPROVED** [review]
@sah0017 LGTM!

**Review by jcallison1 — APPROVED** [review]
@sah0017 LGTM

**Comment by aparriaran** [comment]
@sah0017 I am going to merge this PR!

**Pull request merged**
