### PR TITLE
added code to try and fix the token issue that causes the infinite sp…

### PR DESCRIPTION
**Pull request by sah0017**
…in at checkin.

### CODE REVIEW

**Review by jcallison1 — APPROVED** [review]
@sah0017 LGTM

**Comment by jcallison1** [comment]
Oops, sorry, I accidentally approved before I was ready to. Can you pull master into this branch? I was unable to test the changes because this branch doesn't have docker compose.

**Comment by sah0017** [comment]
@jcallison1 branch should be updated.

**Review by jcallison1 — APPROVED** [review]
@sah0017 LGTM

**Review by jcallison1 — APPROVED** [review]
@sah0017 LGTM

**Review by ebanderson3 — APPROVED** [review]
@sah0017

**Comment by sah0017** [comment]
After 2 code reviews, I am merging this code.

**Pull request merged**
