### PR TITLE
UI proposal   aldo

### PR DESCRIPTION
**Pull request by brianlugo1**
Todos Completed:
[x] Implement install redis-server for MacOS automatically in setupEnv.py.
[x] Implement start redis-server automatically setupEnv.py.
[x] Implement end redis-server automatically setupEnv.py.

### CODE REVIEW

**Comment by sah0017** [comment]
@BradenDuke when do you think you can complete this code review?

**Comment by BradenDuke** [comment]
I was able to start looking at it today. Meeting with Brian to review some questions tomorrow.

**Comment by brianlugo1** [comment]
@aldiux4you After taking a look with Dr. Hammond, it seems we are not calling the bash script that installs home brew. You need to add another line of code that attempts to execute the bash script file.

**Comment by brianlugo1** [comment]
I just added the changes to automatically install redis-server for Linux! The next step is to work on automatically install redis-server for windows!

**Comment by brianlugo1** [comment]
I can confirm that Windows is currently not supported by Redis. Therefore, there is no way to automatically install redis-server for Windows. WSL is the only supported platform by Redis. From here on out, Windows users will need to use WSL to be able to develop using Redis!

**Comment by brianlugo1** [comment]
@sah0017 I am going to go ahead and merge this branch! LGTM

**Pull request merged**
