### PR TITLE
Better error handling

### PR DESCRIPTION
**Pull request by Wrimo**
I had some issues with the new way we were error handling, so I went ahead and made some changes.

* Add a decorator in utility.py that catches errors and logs
* Improved log messages to include file and line information 
* Updated models to user new decorator 

The new decorator is much more scalable than what we were doing. If we want to tweak what we log or how we handle a specific exception, we only have to change it in one place rather than every single model function.

### CODE REVIEW

**Review by malloc-nbytes — CHANGES_REQUESTED** [review]
FrontEndReact/src/View/Login/SetNewPassword.js line 78 is an extra closing div.

**Review by malloc-nbytes — APPROVED** [review]
LGTM

**Review by brianlugo1 — APPROVED** [review]
@sah0017 LGTM!

**Comment by brianlugo1** [comment]
@sah0017 This PR has received two approved code reviews! I am going to go ahead and merge this PR into master!

**Pull request merged**
