### PR TITLE
Fix Rating Errors

### PR DESCRIPTION
**Pull request by brianlugo1**
This pull request fixes the bugs that arose when the change of storing the rating_json in the Category table instead of a whole separate Ratings table was made!

### CODE REVIEW

**Review by malloc-nbytes — APPROVED** [review]
There is a comment saying to "log error InvalidCategoryID", but it isn't actually doing that. But other than that, 

LGTM!

**Review by Wrimo — APPROVED** [review]
Except for the thing @malloc-nbytes mentioned, LGTM.

**Comment by brianlugo1** [comment]
@malloc-nbytes I just removed the unneeded comment!

**Comment by brianlugo1** [comment]
@sah0017 I am going to go ahead and merge this PR because it has received two approved code reviews!

**Pull request merged**
